check_interval = 600 # Unused for now
icons = true
check_locations_recursive = ["~/Programs", "~/Work", "~/Music", "~/Downloads", "~/Documents", "~/Videos", "~/Pictures", "~/.config"]
check_locations = ["~"]
icon_path = "/usr/share/icons/Papirus/32x32/"
allowed_extensions = [".csv", ".txt", ".mp3", ".m4a", ".mp4", ".webm", ".mov", ".avi", ".png", ".webp", ".jpg", ".jpeg", ".inputrc", ".xml", ".css", ".md", ".rc", ".json", ".sh", ".git", ".conf", ".py", ".rasi", ".mk", ".h", ".desktop", ".AppImage", ".crt", ".bash", ".config", ".log", ".tmp", ".ini", ".old", ".code", ".backup", ".vscdb", ".haskell", ".c", ".cnf", ".hs", ".groff", ".java", ".dat", ".js", ".gif", ".html", ".bak", ".ico", ".svg", ".yml", ".cache", ".po", ".Po", ".ac", ".m", ".install", ".x", ".y", ".cabal", ".mdown", ".markdown", ".micro", ".toml", ".orig", ".yaml", ".README", ".bat", ".cpp", ".pl", ".app", ".icns", ".man", ".fish", ".rtf", ".cc", ".d", ".vscode", ".ghc", ".sys", ".ssh", ".pub", ".xinitrc", ".srt", ".kdenlive", ".aac", ".vtt", ".wav", ".ma", ".mkv", ".mozilla", ".dmp", ".co", ".ghcup", ".nanorc", ".pki", ".themes", ".gpg", ".tar", ".gitconfig", ".profile", ".s", ".dmrc", ".nano", ".bashrc", ".lesshst", ".xpm", ".xbm", ".styles", ".layout", ".menu", ".doc", ".htm", ".ogg", ".bmp", ".ods", ".out", ".ms", ".cfg", ".lua", ".go", ".gpx", ".lang", ".m4v", ".pdf", ".rs", ".sql"]

[file_extension_icons]
".csv" = "text-csv.svg"
".txt" = "text-plain.svg"
".mp3" = "audio-mpeg.svg"
".m4a" = "audio-m4a.svg"
".mp4" = "video-mp4.svg"
".webm" = "video-webm.svg"
".mov" = "video-quicktime.svg"
".avi" = "video-x-msvideo.svg"
".png" = "image-png.svg"
".webp" = "image.svg"
".jpg" = "image-jpeg.svg"
".jpeg" = "image-jpeg.svg"
".inputrc" = "application-x-shellscript.svg"
".xml" = "text-xml.svg"
".css" = "text-css.svg"
".md" = "text-markdown.svg"
".rc" = "text-plain.svg"
".json" = "application-json.svg"
".sh" = "application-x-shellscript.svg"
".git" = "text-plain.svg"
".conf" = "text-plain.svg"
".py" = "text-x-python.svg"
".rasi" = "text-plain.svg"
".mk" = "text-plain.svg"
".h" = "text-plain.svg"
".desktop" = "application-x-desktop.svg"
".AppImage" = "application-vnd.appimage.svg"
".crt" = "application-x-x509-ca-cert.svg"
".bash" = "application-x-shellscript.svg"
".config" = "application-xml.svg"
".log" = "text-x-log.svg"
".tmp" = "text-plain.svg"
".ini" = "text-plain.svg"
".old" = "text-plain.svg"
".code" = "text-plain.svg"
".backup" = "text-plain.svg"
".vscdb" = "text-plain.svg"
".haskell" = "text-x-haskell.svg"
".c" = "text-plain.svg"
".cnf" = "text-plain.svg"
".hs" = "text-x-haskell.svg"
".groff" = "text-plain.svg"
".java" = "application-octet-stream.svg"
".dat" = "application-octet-stream.svg"
".js" = "application-javascript.svg"
".gif" = "image-gif.svg"
".html" = "text-html.svg"
".bak" = "text-plain.svg"
".ico" = "image-x-icon.svg"
".svg" = "image-svg+xml.svg"
".yml" = "application-x-yaml.svg"
".cache" = "text-plain.svg"
".po" = "text-x-po.svg"
".Po" = "text-x-po.svg"
".ac" = "text-plain.svg"
".m" = "text-plain.svg"
".install" = "text-x-install.svg"
".x" = "application-directx.svg"
".y" = "text-plain.svg"
".cabal" = "text-plain.svg"
".mdown" = "text-markdown.svg"
".markdown" = "text-markdown.svg"
".micro" = "text-plain.svg"
".toml" = "application-toml.svg"
".orig" = "text-plain.svg"
".yaml" = "application-x-yaml.svg"
".README" = "text-x-readme.svg"
".bat" = "text-plain.svg"
".cpp" = "text-x-c++src.svg"
".pl" = "text-plain.svg"
".app" = "text-plain.svg"
".icns" = "text-plain.svg"
".man" = "application-x-troff-man.svg"
".fish" = "text-plain.svg"
".rtf" = "application-rtf.svg"
".cc" = "text-plain.svg"
".d" = "text-plain.svg"
".vscode" = "text-plain.svg"
".ghc" = "text-plain.svg"
".sys" = "text-plain.svg"
".ssh" = "text-plain.svg"
".pub" = "application-x-mspublisher.svg"
".xinitrc" = "text-plain.svg"
".srt" = "application-x-srt.svg"
".kdenlive" = "application-x-kdenlive.svg"
".aac" = "audio-aac.svg"
".vtt" = "text-vtt.svg"
".wav" = "audio-wav.svg"
".ma" = "text-plain.svg"
".mkv" = "video-x-matroska.svg"
".mozilla" = "text-plain.svg"
".dmp" = "text-plain.svg"
".co" = "text-plain.svg"
".ghcup" = "text-plain.svg"
".nanorc" = "text-plain.svg"
".pki" = "text-plain.svg"
".themes" = "text-plain.svg"
".gpg" = "pgp-encrypted.svg"
".tar" = "application-x-tar.svg"
".gitconfig" = "text-plain.svg"
".profile" = "text-plain.svg"
".s" = "text-plain.svg"
".dmrc" = "application-x-shellscript.svg"
".nano" = "text-plain.svg"
".bashrc" = "application-x-shellscript.svg"
".lesshst" = "application-x-shellscript.svg"
".xpm" = "image-x-xpixmap.svg"
".xbm" = "image-x-xbitmap.svg"
".styles" = "text-plain.svg"
".layout" = "text-plain.svg"
".menu" = "text-plain.svg"
".doc" = "application-msword.svg"
".htm" = "text-html.svg"
".ogg" = "audio-ogg.svg"
".bmp" = "image-bmp.svg"
".ods" = "application-vnd.oasis.opendocument.spreadsheet.svg"
".out" = "text-plain.svg"
".ms" = "application-x-troff-ms.svg"
".cfg" = "text-plain.svg"
".lua" = "text-x-lua.svg"
".go" = "text-x-go.svg"
".gpx" = "application-gpx+xml.svg"
".lang" = "text-plain.svg"
".m4v" = "video-x-m4v.svg"
".pdf" = "application-pdf.svg"
".rs" = "text-rust.svg"
".sql" = "application-sql.svg"

