# jmbi
[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.footer_bar]
background = "#282a36"
foreground = "#f8f8f1"

[colors.hints.end]
background = "#282a36"
foreground = "#f1fa8c"

[colors.hints.start]
background = "#f1fa8c"
foreground = "#22212d"

[colors.line_indicator]
background = "None"
foreground = "None"

# Colors (Gruvbox dark)

# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
background = '#1e1e1e'
# soft contrast background = = '#32302f'
foreground = '#efe2e0'

# Normal colors
[colors.normal]
black   = '#5a7260'
red     = '#8f423c'
green   = '#bbbb88'
yellow  = '#f9d25b'
blue    = '#e0ba69'
magenta = '#709289'
cyan    = '#c25431'
white   = '#efe2e0'

# Bright colors
[colors.bright]
black   = '#5a7260'
red     = '#8f423c'
green   = '#bbbb88'
yellow  = '#f9d25b'
blue    = '#e0ba69'
magenta = '#709289'
cyan    = '#c25431'
white   = '#efe2e0'

[colors.search.focused_match]
background = "#ffb86c"
foreground = "#44475a"

[colors.search.matches]
background = "#50fa7b"
foreground = "#44475a"

[colors.selection]
background = "#44475a"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[cursor.style]
shape = "Beam"
